### ISSUE TITLE
How to solve the problem of Olama error in the Idea editor？

### ISSUE THREAD

**Issue by ToDreamr** [Tencent/vectordatabase-sdk-java#4]
I cloned this repo in my idea,konwing that the olama is the production compiled by protoc,but even though the file like GrpcStub.java has a correct import sentence 'import com.tencent.tcvectordb.rpc.proto.Olama;' and the Olama.java truly exist in the right path ,still the edit report the red wanning ,can not find the file?
Thanks for your help!
![image](https://github.com/user-attachments/assets/a4d1902a-dac8-4eb2-9a86-6083dfe774d5)

**Comment by ToDreamr** [comment]
@anyihao

**Comment by anyihao** [comment]
you need to increase idea compile file&nbsp; size，because the olama file size exceeds the config



---Original---
From: ***@***.***&gt;
Date: Sat, Nov 30, 2024 15:35 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Tencent/vectordatabase-sdk-java] How to solve the problem of Olama error in the Idea editor？ (Issue #4)




 
I cloned this repo in my idea,konwing that the olama is the production compiled by protoc,but even though the file like GrpcStub.java has a correct import sentence 'import com.tencent.tcvectordb.rpc.proto.Olama;' and the Olama.java truly exist in the right path ,still the edit report the red wanning ,can not find the file?
 Thanks for your help!
 image.png (view on web)

**Comment by ToDreamr** [comment]
![image](https://github.com/user-attachments/assets/f062169c-e152-4df5-92e9-e9549f476504)
Solved by designating the absolute path of olama file.Thanks U.

**Comment by ToDreamr** [comment]
Thanks,After I set the config in  idea.properties with idea.max.intellisense.filesize=99999 the Olama.java can be read.
